name: Deploy Lambda to S3
run-name: Deploy application

on:
  workflow_dispatch:


jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip File
        run: zip -r ssp-combiner-lambda.zip . -x "*.git*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Upload to S3 Bucket
        run: aws s3 cp ssp-combiner-lambda.zip s3://${{ secrets.LAMBDA_ARTIFACT_S3_BUCKET_NAME }}/lambda-builds/ssp-combiner-lambda.zip


      - name: Deploy Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --s3-bucket  ${{ secrets.LAMBDA_ARTIFACT_S3_BUCKET_NAME }} \
            --s3-key lambda-builds/ssp-combiner-lambda.zip